CREATE DATABASE Tablevation;
USE Tablevation;

CREATE TABLE Account(
Email VARCHAR(50) PRIMARY KEY, 
Password VARCHAR(20),
User_Type 
)

CREATE TABLE Food_Type(
Food VARCHAR(15) PRIMARY KEY
);

CREATE TABLE Area(
Area_Name VARCHAR(15) PRIMARY KEY
);

CREATE TABLE Restaurant(
Account_Email VARCHAR(50) PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Address_Line1 VARCHAR(50) NOT NULL,
Area_Name VARCHAR(15) NOT NULL,
City VARCHAR(35) DEFAULT 'Portsmouth',
County VARCHAR(35) DEFAULT 'Hampshire',
PostCode VARCHAR(8) NOT NULL,
Contact_Number VARCHAR(15) NOT NULL,
Mon_OT TIME NOT NULL,
Mon_CT TIME NOT NULL,
Tues_OT TIME NOT NULL,
Tues_CT TIME NOT NULL,
Wed_OT TIME NOT NULL,
Wed_CT TIME NOT NULL,
Thur_OT TIME NOT NULL,
Thur_CT TIME NOT NULL,
Fri_OT TIME NOT NULL,
Fri_CT TIME NOT NULL,
Sat_OT TIME NOT NULL,
Sat_CT TIME NOT NULL,
Sun_OT TIME NOT NULL,
Sun_CT TIME NOT NULL,
Rating INT NULL,
Food_Type_Food VARCHAR(15) NOT NULL,
CONSTRAINT FOREIGN KEY (Account_Email) REFERENCES Account(Email),
CONSTRAINT FOREIGN KEY (Area_Name) REFERENCES Area(Area_Name),
CONSTRAINT FOREIGN KEY (Food_Type_Food) REFERENCES Food_Type(Food)
);

CREATE TABLE Customer(
Account_Email VARCHAR(50) PRIMARY KEY,
Forename VARCHAR(50) NOT NULL,
Surname VARCHAR(50) NOT NULL,
Contact_Number VARCHAR(15) NOT NULL,
CONSTRAINT FOREIGN KEY (Account_Email) REFERENCES Account(Email)
);

CREATE TABLE Reservation(
Restaurant_Name VARCHAR(50) NOT NULL,
Restaurant_Area
Account_Email VARCHAR(50) NOT NULL,
Booked_Time TIME NOT NULL,
Booked_Date DATE NOT NULL,
No_Guests int NOT NULL,
Details VARCHAR(100) NULL,
CONSTRAINT FOREIGN KEY (Account_Email) REFERENCES Account(Email)
CONSTRAINT FOREIGN KEY (Restaurant_Name) REFERENCES Restaurant(Name)
CONSTRAINT FOREIGN KEY (Restaurant_Area) REFERENCES Restaurant(Area)
);

